language: java
sudo: false
install: true

addons:
    sonarcloud:
        organization: "maxamel-github"
        token:
            secure: "tqkFOwk6zLp+tunh5H4I6O5ttUzr9moZ3pKFd7vLdCMwco0RPQu+DYYDqESEsPD419ZkgJLENWCb8ihnhpnK/iYl5GADKUf8yyh49A3qIABZSqEVdGwBrwUJrX40Z0FxwwRNcwocnLZoqXjZOJiI4V7+q3yBRIeKkCyOg8aRqY0y5Rg1FnH6Mz+2vCWn+FW8jwJoV2LztdjnA8Zdg57hSsoL2ILUzt9fQ0LaFkQvvbJmemnrwZd6M/F9L2SI+x102d7uC01cOfr4qZfSxqPliO/VtQJ9w1Uoq2SqQYBTisuSgZiUCHRuk5aVpberc15JVJUJywZC7ZjHQp0tE+MtftnNl/ZBp/D6gJ8+vHr6R6wEC9APcesf2fdWgba6+sfPvJH3UpUOzwSEdFT0i0AOseFWaVm3znM1zCIwV+k3aSXz3PK6sLH1iDWAnL/oc/p6S3PUaaLpXx9mz6rcS2PN6GTi5XPMMcRZdcbAw6Rlz15pYh5vEmF8PEVY9v3TpjbaexgIwDr1x1UAPrAraoqHBZLAme1vs0oYVqpT+WBcuYhbKsGcCorB4S6fV3UsV9cP/+xeLGyoWHJfStxnJfER+mm/g+1IhvIUqbJhaGLpo3pP61zaimhXXChaplvsgtPjXvX3NdImErhqng5Lib3I7GE9ur5zFzIAGoh1oHNgSck="

jdk:
  - oraclejdk8
  - openjdk8
  
script:
  - ./gradlew sonarqube
