language: java
sudo: false
install:
  - npm install

addons:
    sonarcloud:
        organization: "maxamel-github"
        token: $SONAR_TOKEN

jdk:
  - oraclejdk8
  - openjdk8
  
script:
  - ./gradlew sonarqube
  - snyk test

cache:
directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
