language: java
jdk:
  - oraclejdk8
  - openjdk8

addons:
    sonarqube: true
    
after_success:
    gradle check
    gradle sonarqube -Dsonar.host.url=$SONAR_HOST -Dsonar.login=$SONAR_TOKEN -Dsonar.verbose=true